<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import tensorflow as tf
tf.__version__

'2.0.0'

In [3]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
#importing the data
df_bank = pd.read_csv(r'C:\Users\Tamanna Kawatra\OneDrive\Desktop\ML\Churn_Modelling.csv')

In [25]:
df_bank.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [26]:
x = df_bank.iloc[:,3:13].values
y = df_bank.iloc[:,13].values
x
x.shape

(10000, 10)

In [27]:
#encoding categorical variables
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer



labelencoder_x_1 = LabelEncoder()
x[:,1] = labelencoder_x_1.fit_transform(x[:,1])
labelencoder_x_2 = LabelEncoder()
x[:,2] = labelencoder_x_2.fit_transform(x[:,2])
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [28]:
#onehot encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer



ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [1,2])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)

x = ct.fit_transform(x)



In [29]:
x = x[:, 1:]
x

array([[0.0, 0.0, 1.0, ..., 1, 1, 101348.88],
       [0.0, 1.0, 1.0, ..., 0, 1, 112542.58],
       [0.0, 0.0, 1.0, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 1.0, ..., 0, 1, 42085.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 92888.52],
       [0.0, 0.0, 1.0, ..., 1, 0, 38190.78]], dtype=object)

In [30]:
x.shape

(10000, 12)

In [31]:
x[:, 0:12]

array([[0.0, 0.0, 1.0, ..., 1, 1, 101348.88],
       [0.0, 1.0, 1.0, ..., 0, 1, 112542.58],
       [0.0, 0.0, 1.0, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 1.0, ..., 0, 1, 42085.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 92888.52],
       [0.0, 0.0, 1.0, ..., 1, 0, 38190.78]], dtype=object)

In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [36]:
import tensorflow as tf

from tensorflow import keras

In [37]:
from tensorflow.keras import layers


In [38]:
classifier = tf.keras.Sequential()

In [39]:
from tensorflow.keras.layers import Flatten,Dense

In [40]:
classifier.add(Flatten(input_shape = (12,)))
classifier.add(Dense(5, activation = 'relu'))
classifier.add(Dense(5, activation = 'relu'))
classifier.add(Dense(1, activation = 'sigmoid'))

In [41]:
classifier.summary

<bound method Network.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x000002012C49BBC8>>

In [42]:
classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [43]:
classifier.fit(x_train, y_train, epochs = 20)

Train on 8000 samples
Epoch 1/20
8000/8000 [==============================] - 2s 223us/sample - loss: 0.7835 - accuracy: 0.5038
Epoch 2/20
8000/8000 [==============================] - 1s 68us/sample - loss: 0.5352 - accuracy: 0.7901
Epoch 3/20
8000/8000 [==============================] - 1s 72us/sample - loss: 0.4886 - accuracy: 0.7960
Epoch 4/20
8000/8000 [==============================] - 0s 62us/sample - loss: 0.4713 - accuracy: 0.7960
Epoch 5/20
8000/8000 [==============================] - 0s 54us/sample - loss: 0.4587 - accuracy: 0.7960
Epoch 6/20
8000/8000 [==============================] - 1s 73us/sample - loss: 0.4477 - accuracy: 0.7965
Epoch 7/20
8000/8000 [==============================] - 1s 71us/sample - loss: 0.4376 - accuracy: 0.8014
Epoch 8/20
8000/8000 [==============================] - 1s 75us/sample - loss: 0.4287 - accuracy: 0.8055
Epoch 9/20
8000/8000 [==============================] - 1s 72us/sample - loss: 0.4220 - accuracy: 0.8145
Epoch 10/20
8000/8000 [=========

In [44]:
y_pred = classifier.predict(x_test)
y_pred[:10]

array([[0.24252152],
       [0.4271313 ],
       [0.21055108],
       [0.07986456],
       [0.15137872],
       [0.3693164 ],
       [0.06341267],
       [0.10590294],
       [0.6012793 ],
       [0.3693164 ]], dtype=float32)

In [45]:
y_pred = (y_pred > 0.3)
y_pred[:10]

array([[False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True]])

In [46]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1315,  280],
       [ 135,  270]], dtype=int64)

In [47]:
#Performance Parameters
from sklearn.datasets import make_circles
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(y_test,y_pred)
print('Accuracy: %f' % accuracy)
# precision tp / (tp + fp)
precision = precision_score(y_test,y_pred)
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(y_test,y_pred)
print('Recall: %f' % recall)
f1 = f1_score(y_test,y_pred)
print('F1 score: %f' % f1)

Accuracy: 0.792500
Precision: 0.490909
Recall: 0.666667
F1 score: 0.565445
